DELETE IF EXISTS FAMILY_DB;

CREATE DATABASE FAMILY_DB;

USE FAMILY_DB;

CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  joincode TEXT NOT NULL,
  isConfirmed BOOLEAN NOT NULL,
  firstname TEXT NOT NULL,
  lastname TEXT NOT NULL,
  address TEXT NOT NULL,
  email TEXT NOT NULL,
  dob DATE NOT NULL,
  confirmedBy TEXT NULL
  PRIMARY KEY (id)
);

CREATE TABLE calendar (
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    joincode TEXT NOT NULL,
    event TEXT NOT NULL,
    eventDate DATE NOT NULL,
    eventTime: DATETIME NOT NULL
);

CREATE TABLE wishes (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);