DELETE IF EXISTS FAMILY_DB;

CREATE DATABASE FAMILY_DB;

USE FAMILY_DB;

CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT,
  last_name VARCHAR(250) NULL,
   NULL,
  quantity INT NULL,
  PRIMARY KEY (id)
);
